Series和Datafram索引的原理一样，我们以Dataframe的索引为主来学习
* 列索引：df['列名']  （Series不存在列索引）
* 行索引：df.loc[]、df.iloc[]

选择列 / 选择行 / 切片 / 布尔判断

In [1]:
import numpy as np
import pandas as pd  
# 导入numpy、pandas模块

In [5]:
# 选择行与列

df = pd.DataFrame(np.random.rand(12).reshape(3,4)*100,
                   index = ['one','two','three'],
                   columns = ['a','b','c','d'])
print(df)


data1 = df['a']
data2 = df[['a','c']]
print(data1,type(data1))
print(data2,type(data2))
print('---------------------------------------------------------------------')
# 按照列名选择列，只选择一列输出Series，选择多列输出Dataframe

data3 = df.loc['one']
data4 = df.loc[['one','two']]
print(data2,type(data3))
print(data3,type(data4))
# 按照index选择行，只选择一行输出Series，选择多行输出Dataframe

               a          b          c          d
one    55.716857  28.670699  53.462274  17.771688
two    25.801905  20.939987  32.648866  41.682242
three  13.653587  36.973833  86.219628  64.060519
one      55.716857
two      25.801905
three    13.653587
Name: a, dtype: float64 <class 'pandas.core.series.Series'>
               a          c
one    55.716857  53.462274
two    25.801905  32.648866
three  13.653587  86.219628 <class 'pandas.core.frame.DataFrame'>
---------------------------------------------------------------------
               a          c
one    55.716857  53.462274
two    25.801905  32.648866
three  13.653587  86.219628 <class 'pandas.core.series.Series'>
a    55.716857
b    28.670699
c    53.462274
d    17.771688
Name: one, dtype: float64 <class 'pandas.core.frame.DataFrame'>

In [10]:
# df[] - 选择列
# 一般用于选择列，也可以选择行，但不推荐，行索引用.loc与.iloc

df = pd.DataFrame(np.random.rand(12).reshape(3,4)*100,
                   index = ['one','two','three'],
                   columns = ['a','b','c','d'])
print(df)
print('---------------------------------------------------')

data1 = df['a']
data2 = df[['b','c']]  # 尝试输入 data2 = df[['b','c','e']]
print(data1)
print(data2)
# df[]默认选择列，[]中写列名（所以一般数据colunms都会单独制定，不会用默认数字列名，以免和index冲突）
# 单选列为Series，print结果为Series格式
# 多选列为Dataframe，print结果为Dataframe格式

# 核心笔记：df[col]一般用于选择列，[]中写列名

               a          b          c          d
one    41.476281   8.436923  55.371092  90.263709
two    64.402973  84.150319  99.669509  96.921969
three  37.537311  13.227073  50.046925  32.031111
---------------------------------------------------
one      41.476281
two      64.402973
three    37.537311
Name: a, dtype: float64
               b          c
one     8.436923  55.371092
two    84.150319  99.669509
three  13.227073  50.046925

In [15]:
# df.loc[] - 按index选择行

df1 = pd.DataFrame(np.random.rand(16).reshape(4,4)*100,
                   index = ['one','two','three','four'],
                   columns = ['a','b','c','d'])
df2 = pd.DataFrame(np.random.rand(16).reshape(4,4)*100,
                   columns = ['a','b','c','d'])
print(df1)
print(df2)
print('-------------------------------------------------------')

data1 = df1.loc['one']
data2 = df2.loc[1]
print(data1)
print(data2)
print('单标签索引\n-------------------------------------------------------')
# 单个标签索引，返回Series

data3 = df1.loc[['two','three','five']]
data4 = df2.loc[[3,2,1]]
print(data3)
print(data4)
print('多标签索引\n-----------------------------------------------------------')
# 多个标签索引，如果标签不存在，则返回NaN
# 顺序可变
# 这里‘five’标签不存在，所以有警告

data5 = df1.loc['one':'three']
data6 = df2.loc[1:3]
print(data5)
print(data6)
print('切片索引--------------------------------------------------------------')
# 可以做切片对象
# 末端包含

# 核心笔记：df.loc[label]主要针对index选择行，同时支持指定index，及默认数字index

               a          b          c          d
one    53.744055  99.557268   4.856367  91.207507
two    56.517066  57.124716  97.295641  98.755174
three  82.771430  88.597825  10.775099  37.306822
four   97.114897   1.862673  92.570304  91.673153
           a          b          c          d
0  87.143450  16.819112  19.123219  84.192627
1  15.744214  37.001708  25.307065  20.089021
2  28.326192  50.922801  68.821992  33.150144
3  10.867265  21.569084   8.258500  85.070664
-------------------------------------------------------
a    53.744055
b    99.557268
c     4.856367
d    91.207507
Name: one, dtype: float64
a    15.744214
b    37.001708
c    25.307065
d    20.089021
Name: 1, dtype: float64
单标签索引
-------------------------------------------------------
               a          b          c          d
two    56.517066  57.124716  97.295641  98.755174
three  82.771430  88.597825  10.775099  37.306822
five         NaN        NaN        NaN        NaN
           a          b          c          d
3  10.867265  21.569084   8.258500  85.070664
2  28.326192  50.922801  68.821992  33.150144
1  15.744214  37.001708  25.307065  20.089021
多标签索引
-----------------------------------------------------------
               a          b          c          d
one    53.744055  99.557268   4.856367  91.207507
two    56.517066  57.124716  97.295641  98.755174
three  82.771430  88.597825  10.775099  37.306822
           a          b          c          d
1  15.744214  37.001708  25.307065  20.089021
2  28.326192  50.922801  68.821992  33.150144
3  10.867265  21.569084   8.258500  85.070664
切片索引--------------------------------------------------------------

D:\Python3.6.2\lib\site-packages\ipykernel_launcher.py:19: FutureWarning:
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike

In [19]:
# df.iloc[] - 按照整数位置（从轴的0到length-1）选择行
# 类似list的索引，其顺序就是dataframe的整数位置，从0开始计

df = pd.DataFrame(np.random.rand(16).reshape(4,4)*100,
                   index = ['one','two','three','four'],
                   columns = ['a','b','c','d'])
print(df)
print('----------------------------------------------------')

print(df.iloc[0])
print(df.iloc[-1])
#print(df.iloc[4])
print('单位置索引\n------------------------------------------------------')
# 单位置索引
# 和loc索引不同，不能索引超出数据行数的整数位置

print(df.iloc[[0,2]])
print(df.iloc[[3,2,1]])
print('多位置索引\n------------------------------------------------------')
# 多位置索引
# 顺序可变

print(df.iloc[1:3])
print(df.iloc[::2])
print('切片索引----------------------------------------------------------')
# 切片索引
# 末端不包含

               a          b          c          d
one    36.840186  47.330558   1.068671   7.907847
two     2.537323  54.266870  18.269840  84.027046
three  40.554966   3.964787  36.283338  65.474042
four    9.552209  38.383802  77.983668  59.378166
----------------------------------------------------
a    36.840186
b    47.330558
c     1.068671
d     7.907847
Name: one, dtype: float64
a     9.552209
b    38.383802
c    77.983668
d    59.378166
Name: four, dtype: float64
单位置索引
------------------------------------------------------
               a          b          c          d
one    36.840186  47.330558   1.068671   7.907847
three  40.554966   3.964787  36.283338  65.474042
               a          b          c          d
four    9.552209  38.383802  77.983668  59.378166
three  40.554966   3.964787  36.283338  65.474042
two     2.537323  54.266870  18.269840  84.027046
多位置索引
------------------------------------------------------
               a          b          c          d
two     2.537323  54.266870  18.269840  84.027046
three  40.554966   3.964787  36.283338  65.474042
               a          b          c          d
one    36.840186  47.330558   1.068671   7.907847
three  40.554966   3.964787  36.283338  65.474042
切片索引----------------------------------------------------------

In [24]:
# 布尔型索引
# 多用于索引行

df = pd.DataFrame(np.random.rand(16).reshape(4,4)*100,
                   index = ['one','two','three','four'],
                   columns = ['a','b','c','d'])
print(df)
print('------------------------------------------------------------')

b1 = df < 20
print(b1,type(b1))
print(df[b1])  # 也可以书写为 df[df < 20]
print('------------------------------------------------------------')
# 不做索引则会对数据每个值进行判断
# 索引结果保留 所有数据：True返回原数据，False返回值为NaN

b2 = df['a'] > 50
print(b2,type(b2))
print(df[b2])  # 也可以书写为 df[df['a'] > 50]
print('------------------------------------------------------------')
# 单列做判断
# 索引结果保留 单列判断为True的行数据，包括其他列

b3 = df[['a','b']] > 50
print(b3,type(b3))
print(df[b3])  # 也可以书写为 df[df[['a','b']] > 50]
print('-------------------------------------------------------------')
# 多列做判断
# 索引结果保留 所有数据：True返回原数据，False返回值为NaN
# 注意这里报错的话，更新一下pandas → conda update pandas

b4 = df.loc[['one','three']] < 50
print(b4,type(b4))
print(df[b4])  # 也可以书写为 df[df.loc[['one','three']] < 50]
print('------------------------------------------------------------')
# 多行做判断
# 索引结果保留 所有数据：True返回原数据，False返回值为NaN

               a          b          c          d
one    24.929308  27.323073   2.526231  51.992177
two    99.620967  80.217655   1.257165  18.059365
three  71.371687  43.041270  64.475249  69.616920
four   78.870258  26.814066  64.576008  70.304935
------------------------------------------------------------
           a      b      c      d
one    False  False   True  False
two    False  False   True   True
three  False  False  False  False
four   False  False  False  False <class 'pandas.core.frame.DataFrame'>
        a   b         c          d
one   NaN NaN  2.526231        NaN
two   NaN NaN  1.257165  18.059365
three NaN NaN       NaN        NaN
four  NaN NaN       NaN        NaN
------------------------------------------------------------
one      False
two       True
three     True
four      True
Name: a, dtype: bool <class 'pandas.core.series.Series'>
               a          b          c          d
two    99.620967  80.217655   1.257165  18.059365
three  71.371687  43.041270  64.475249  69.616920
four   78.870258  26.814066  64.576008  70.304935
------------------------------------------------------------
           a      b
one    False  False
two     True   True
three   True  False
four    True  False <class 'pandas.core.frame.DataFrame'>
               a          b   c   d
one          NaN        NaN NaN NaN
two    99.620967  80.217655 NaN NaN
three  71.371687        NaN NaN NaN
four   78.870258        NaN NaN NaN
-------------------------------------------------------------
           a     b      c      d
one     True  True   True  False
three  False  True  False  False <class 'pandas.core.frame.DataFrame'>
               a          b         c   d
one    24.929308  27.323073  2.526231 NaN
two          NaN        NaN       NaN NaN
three        NaN  43.041270       NaN NaN
four         NaN        NaN       NaN NaN
------------------------------------------------------------

In [27]:
# 多重索引：比如同时索引行和列
# 先选择列再选择行 —— 相当于对于一个数据，先筛选字段，再选择数据量

df = pd.DataFrame(np.random.rand(16).reshape(4,4)*100,
                   index = ['one','two','three','four'],
                   columns = ['a','b','c','d'])
print(df)
print('-----------------------------------------------------------')


print(df['a'].loc[['one','three']])   # 选择a列的one，three行
print(df[['b','c','d']].iloc[::2])   # 选择b，c，d列的one，three行
print(df[df['a'] < 50].iloc[:2])   # 选择满足判断索引的前两行数据

               a          b          c          d
one    72.216286  33.915793  71.022793  46.075476
two    87.174350  50.881006  19.100023  85.530496
three  14.251046  38.475553  29.580271  91.124349
four   32.344990  24.293926  18.734200  85.673837
-----------------------------------------------------------
one      72.216286
three    14.251046
Name: a, dtype: float64
               b          c          d
one    33.915793  71.022793  46.075476
three  38.475553  29.580271  91.124349
               a          b          c          d
three  14.251046  38.475553  29.580271  91.124349
four   32.344990  24.293926  18.734200  85.673837

######## 课后小练习,请查看 “pandas课程作业.docx”  ########

作业1：如图创建Dataframe(4*4，值为0-100的随机数)，通过索引得到以下值
* 索引得到b，c列的所有值
* 索引得到第三第四行的数据
* 按顺序索引得到two，one行的值
* 索引得到大于50的值

作业2：创建一个Series，包含10个元素，且每个值为0-100的均匀分布随机值，index为a-j，请分别筛选出：
* 标签为b，c的值为多少
* Series中第4到6个值是哪些？
* Series中大于50的值有哪些？